name: autopay-subscription-indexer
description: "Indexes events from the SubscriptionManager contract for the AutoPay agent"

networks:
  - id: 10143 # Monad Testnet Chain ID
    rpc: https://testnet-rpc.monad.xyz
    # IMPORTANT: Make sure this is the block number where you deployed the LATEST contract
    start_block: 41931355 
    contracts:
      - name: SubscriptionManager
        # IMPORTANT: Make sure this is the address of your LATEST deployed contract
        address: "0x49A341568e5447719c66d135B24bECaCae3feCc5" 
        handler: ./src/EventHandlers.ts
        events:
          # 👇 --- THE FIX: 'recipient' is NOT indexed ---
          - event: "SubscriptionCreated(uint256 indexed subscriptionId, address indexed owner, address indexed subscriber, address recipient, address token, uint256 amount, uint256 frequency)"
          - event: "SubscriptionCancelled(uint256 indexed subscriptionId, address indexed subscriber)"
          - event: "PaymentMade(uint256 indexed subscriptionId, address indexed subscriber, uint256 amount, uint256 paymentTimestamp)"

