name: auto-revoke-approval-indexer
description: "Indexer for all ERC20 Approval events on Monad Testnet"
networks:
  - id: 10143
    rpc: https://testnet-rpc.monad.xyz
    start_block: 40000000
    contracts:
      - name: ERC20
        handler: ./src/EventHandlers.ts
        events:
          - event: "Approval(address indexed owner, address indexed spender, uint256 value)"
